export class Mamlz {
  mm_primno?: number;
  srk_no?: number = 0;
  mm_tur?: number = 0;
  mm_kod?: string = '';
  mm_ad?: string = '';
  mm_cins?: string = '';
  mm_orjkod?: string = '';
  mm_grp_primno?: number = 0;
  mm_grp?: string = '';
  mm_grp1_primno?: number = 0;
  mm_grp1_kod?: string = '';
  mm_mlz_tur?: string = '';
  mm_brmgrp?: string = '';
  mm_boyacarp?: number = 0;
  mm_birim?: string = '';
  mm_birim2?: string = '';
  mm_birim3?: string = '';
  mm_brmcarp?: number = 0;
  mm_stokyeri?: string = '';
  mm_fire?: number = 0;
  mm_minstk?: number = 0;
  mm_ted_frm_kod?: string = '';
  mm_kdv?: number = 0;
  mm_alis_trh?: string = '';
  mm_alis_fiyat?: number = 0;
  mm_alis_dvz_kod?: string = '';
  mm_satis_fiyat?: number = 0;
  mm_satis_dvz_kod?: string = '';
  mm_dp_no?: number = 0;
  mm_grmj?: number = 0;
  mm_metretul?: number = 0;
  mm_grmj2?: number = 0;
  mm_cl_primno?: number = 0;
  mm_cl_kod?: string = '';
  mm_tlmt_primno?: number = 0;
  mm_tlmt_kod?: string = '';
  mm_kg_top?: number = 0;
  mm_kalinlik?: number = 0;
  mm_boy?: number = 0;
  mm_en?: number = 0;
  mm_des_primno?: number = 0;
  mm_des_kod?: string = '';
  uk?: string = '';
  updt?: string = '';
  iuk?: string = '';
  idt?: string = '';
  mm_barkod?: string = '';
  mm_uretici?: string;
  mm_standart?: string;
  mm_ad_ydil?: string;
  mm_muh_sat_hesno?: string;
  mm_muh_stok_kod?: string;
  mm_mkt_kg?: number | null = null;
  mm_bmkt_kg?: number | null = null;
  mm_ipno?: string;
  mm_oto_isrt?: number | null = null;
  mm_yok?: number | null = null;
  mm_i1?: number | null = null;
  mm_i2?: number | null = null;
  mm_i3?: number | null = null;
  mm_v1?: string;
  mm_v2?: string;
  mm_v3?: string;
  mm_g1?: string;
  mm_g2?: string;
  mm_g3?: string;
  mm_g4?: string;
  mm_g5?: string;
  mm_g6?: string;
  mm_g7?: string;
  mm_g8?: string;
  mm_g9?: string;
  mm_g10?: string;
  mm_g11?: string;
  mm_g12?: string;
  mm_g13?: string;
  mm_g14?: string;
  mm_tutar_b?: number | null = null;
  mm_tutar_a?: number | null = null;
  mm_ab_kod?: string;
  mm_kap_band?: string;
  mm_pul_vur?: number | null = null;
  mm_kord_vur?: number | null = null;
  mm_suz_vur?: number | null = null;
  mm_kasy_sol?: number | null = null;
  mm_kasy_sag?: number | null = null;
  mm_kasd_up?: number | null = null;
  mm_kasd_down?: number | null = null;
  mm_devir?: number | null = null;
  mm_ip_kes?: number | null = null;
  mm_pul_devir?: number | null = null;
  mm_kord_devir?: number | null = null;
  mm_suzme_devir?: number | null = null;
  mm_kumas_ger?: number | null = null;
  mm_kas_cevir?: number | null = null;
  mm_mekik_degis?: number | null = null;
  mm_ciz_mly?: number | null = null;
  mm_punch_mly?: number | null = null;
  mm_ciz_trh?: Date | null = null;
  mm_punch_trh?: Date | null = null;
  mm_per_ciz?: number | null = null;
  mm_per_punch?: number | null = null;
  mm_tas_no?: string;
  mm_mak_kod?: string;
  mm_muh_akod?: string;
  mm_demirbas?: number | null = null;
  mm_demirbas_kod?: string;
  mm_amortis_tur?: number | null = null;
  mm_amortis_sure?: number | null = null;
  mm_amortis_hurda_sure?: number | null = null;
  mm_gtip_kod?: string;
  mm_stk_mkt_gir?: number | null = null;
  mm_stk_mkt_cik?: number | null = null;
  mm_stk_mkt_mt_gir?: number | null = null;
  mm_stk_mkt_mt_cik?: number | null = null;
  mm_stk_mkt_amb_gir?: number | null = null;
  mm_stk_mkt_amb_cik?: number | null = null;
  mm_yuzey?: string;
  mm_boya_kalite?: string;
  mm_coz_kod?: string;
  mm_tarak_no?: number | null = null;
  mm_dis_tel?: number | null = null;
  mm_coz_sklik?: number | null = null;
  mm_kenar_tel?: number | null = null;
  mm_coz_buz?: number | null = null;
  mm_coz_fazla?: number | null = null;
  mm_kumas_coz_sklik?: number | null = null;
  mm_hasil_al_oran?: number | null = null;
  mm_cozgu_rapor_en?: number | null = null;
  mm_tarak_en?: number | null = null;
  mm_coz_hen?: number | null = null;
  mm_coz_men?: number | null = null;
  mm_coz_hgr?: number | null = null;
  mm_coz_mgr?: number | null = null;
  mm_coz_tel?: number | null = null;
  mm_coz_rapor_tel?: number | null = null;
  mm_orgu_sekli?: string;
  mm_atki_sklik?: number | null = null;
  mm_atki_buz?: number | null = null;
  mm_atki_fazla?: number | null = null;
  mm_atki_ort_sklik?: number | null = null;
  mm_atki_mam_sklik?: number | null = null;
  mm_atki_devir?: number | null = null;
  mm_atki_rapor_boy?: number | null = null;
  mm_aciklama1?: string;
  mm_aciklama2?: string;
  mm_atki_rapor_tel_sayisi?: number | null = null;
  mm_tahar_kodu?: string;
  mm_armur_kodu?: string;
  mm_satici?: string;
  mm_alis_trh_kur?: number | null = null;
  mm_gayrimenkul?: number | null = null;
  mm_amortisman?: number | null = null;
  mm_kistalyum?: number | null = null;
  mm_sp_id?: number | null = null;
  mm_sp_no1?: number | null = null;
  mm_sp_no2?: number | null = null;
  mm_tesv_id?: number | null = null;
  mm_tesv_no?: number | null = null;
  mm_finansal_kira_no?: number | null = null;
  mm_masraf_merkezi?: string;
  mm_belge_no?: string;
  mm_ted_gun?: number | null = null;
  mm_alasim?: string;
  mm_termik?: string;
  mm_yil?: number | null = null;
  mm_res_en?: number | null = null;
  mm_res_boy?: number | null = null;
  mm_alis_ilk_fiyat?: number | null = null;
  mm_alis_mkt?: number | null = null;
  mm_mas_id?: number | null = null;
}
