export class StokPrt {
  sprt_srk_no: number;
  sprt_bcmno: number;
  sprt_yil: number;
  sprt_dp_no: number;
  sprt_frm_kod: string;
  sprt_mm_primno: number;
  sprt_partino: string;
  sprt_lotno: string;
  sprt_harmanno: string;
  sprt_klt_drm: number;
  sprt_birim: string;
  sprt_amblj_birim: string;
  sprt_grp_partino: string = "";
  sprt_mm_tur: number = 0;
  sprt_mm_kod: string = "";
  sprt_mkt_gir: number = 0;
  sprt_mkt_gir_mt: number = 0;
  sprt_mkt_gir_top: number = 0;
  sprt_mkt_gir_amb: number = 0;
  sprt_brtmkt_gir: number = 0;
  sprt_tutar_gir: number = 0;
  sprt_mkt_cik: number = 0;
  sprt_mkt_cik_mt: number = 0;
  sprt_mkt_cik_top: number = 0;
  sprt_mkt_cik_amb: number = 0;
  sprt_brtmkt_cik: number = 0;
  sprt_tutar_cik: number = 0;
  sprt_tup_may: string = "";
  sprt_grmj: number = 0;
  sprt_en: number = 0;
  sprt_pus: number = 0;
  sprt_fayn: number = 0;
  sprt_metretul: number = 0;
  sprt_cl_primno: number = 0;
  sprt_cl_kod: string = "";
  sprt_tlmt_primno: number = 0;
  sprt_tlmt_kod: string = "";
  sprt_mark_kod: string = "";
  sprt_spd_primno: number = 0;
  sprt_spd_no1: number = 0;
  sprt_spd_sipno: number = 0;
  sprt_fspd_primno: number = 0;
  sprt_fspd_no1: number = 0;
  sprt_fspd_sipno: number = 0;
  sprt_rspd_primno: number = 0;
  sprt_rspd_no1: number = 0;
  sprt_rspd_sipno: number = 0;
  sprt_saspd_primno: number = 0;
  sprt_saspd_no1: number = 0;
  sprt_saspd_sipno: number = 0;
  sprt_tms_kod: string = "";
  sprt_gsb_kod: string = "";
  sprt_irs_trh: Date | null = null;
  sprt_irs_frm_kod: string = "";
  sprt_irs_no: number = 0;
  sprt_stk_yer1: string = "";
  sprt_primno: number;
  sprt_orgu_frm_kod: string = "";
  sprt_mak_kod: string = "";
  sprt_aciklama: string = "";
  sprt_sp_frm_kod: string = "";
  sprt_sa_id: number = 0;
  sprt_sa_mkt: number = 0;
  sprt_sa_fyt: number = 0;
  sprt_sa_dvz_kod: string = "";
  sprt_sa_fyt_tl: number = 0;
  sprt_sa_irsno: number = 0;
  sprt_sa_irs_trh: Date | null = null;
  sprt_sa_frm_kod: string = "";
  sprt_iade_mkt: number = 0;
  sprt_iade_tutar_tl: number = 0;
  sprt_mlyt_fyt: number = 0;
  sprt_mlyt_dvz_kod: string = "";
  sprt_mlyt_fyt_tl: number = 0;
  sprt_mlyt_tutar: number = 0;
  sprt_mlyt_tutar_tl: number = 0;
  sprt_des_id: number = 0;
  sprt_des_kod: string = "";
  sprt_varyant: string = "";
  sprt_ack2: string = "";
  sprt_ip_uzun: string = "";
  sprt_fsw_bcmno: number = 0;
  sprt_fsw_wno: number = 0;
  sprt_frm_sipno: string = "";
  sprt_sfd_id: number = 0;
  sprt_sfd_fis_trh: Date | null = null;
  sprt_sfd_utrh: Date | null = null;
  sprt_amb_trh: Date | null = null;
  sprt_iade_trh: Date | null = null;
  sprt_iade_amb: number = 0;
  sprt_sonkul_trh: Date | null = null;
  sprt_cfyg_id: number = 0;
  sprt_batchno: string = "";
  sprt_eirs_no: string = "";
  sprt_kartela: string = "";
  sprt_sw_wno: number = 0;
  sprt_sw_id: number = 0;
  sprt_bed_set: string = "";
  sprt_bed_acik: string = "";
  sprt_bed_kod: string = "";
}
